"""
VORA - Ollama Model Connector

This file connects VORA to a local Ollama model.

Important:
- Ollama runs locally on your system.
- The API URL uses localhost, so it is offline.
- No cloud API is used.
"""

import requests


# Local Ollama API endpoint
OLLAMA_API_URL = "http://localhost:11434/api/generate"

# Default model name installed in Ollama
MODEL_NAME = "llama3"


def ask_ollama(prompt):
    """
    Send a prompt to the local Ollama model and return the response.

    Args:
        prompt (str): User input.

    Returns:
        str: Response generated by the local Ollama model.
    """

    if not prompt or not prompt.strip():
        return "Please enter a valid prompt."

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(
            OLLAMA_API_URL,
            json=payload,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        return data.get("response", "No response received from Ollama.")

    except requests.exceptions.ConnectionError:
        return (
            "Error: Could not connect to Ollama.\n"
            "Make sure Ollama is running using: ollama serve"
        )

    except requests.exceptions.Timeout:
        return "Error: Ollama took too long to respond."

    except requests.exceptions.HTTPError as error:
        return f"HTTP error from Ollama: {error}"

    except Exception as error:
        return f"Unexpected error while communicating with Ollama: {error}"


def change_model(model_name):
    """
    Change the active Ollama model.

    Args:
        model_name (str): Name of the Ollama model.

    Returns:
        str: Status message.
    """

    global MODEL_NAME

    if not model_name or not model_name.strip():
        return "Invalid model name."

    MODEL_NAME = model_name.strip()
    return f"Model changed to: {MODEL_NAME}"


def get_current_model():
    """
    Return the currently selected model.

    Returns:
        str: Current model name.
    """

    return MODEL_NAME


